os:
  - linux
  - windows
language: rust
rust:
  - stable
  - beta
  - nightly
cache: 
  cargo: true
  timeout: 1000
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
    - libusb-1.0
    - libusb-dev
script:
  - cargo test
