[package]
name = "probe-rs-debugadapter"
version = "0.1.0"
authors = ["Dominik Boehi <dominik.boehi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "*"
debugserver-types = "0.5.0"
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }
log = "*"
simplelog = "0.7.1"
clap = "2.33.0"

probe-rs = { git = "https://github.com/probe-rs/probe-rs", branch="add-source-breakpoints" }


[dev-dependencies]
assert_cmd = "0.10"
insta = "0.11.0"
