name: Rust Build

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest 

    steps:
    - name: Install libusb
      run: sudo apt install -y libusb-dev libusb-1.0
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

  windows-build:
    strategy:
      matrix:
        toolchain:
          - stable-msvc
          - stable-gnu

    runs-on: windows-latest 

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with: 
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
