name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libusb
      run: sudo apt install -y libusb-dev libusb-1.0
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
